# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiapp.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvas
from matplotlib.figure import Figure
from colorbar import ImageColorbar

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1033, 841)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/5f5a7517edd35e8a3a468aca_dark.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color : #EF233C;\n"
"    font: 14px \"Inter\";\n"
"    color : white ; \n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"    color : black ;\n"
"    background-color : none ;\n"
"}\n"
"\n"
"\n"
"QPushButton{ \n"
"    background-color: rgba(255,255,255,255) ;\n"
"    border-radius: 5px;\n"
"    color : black ;\n"
"    border: none;\n"
"    padding-top : 7px ;\n"
"    padding-bottom : 7px ;\n"
"    padding-right : 27px ;\n"
"    padding-left : 27px ;\n"
"    border-radius: 24px;\n"
"    font-family: \'Poppins\';\n"
"    font-style: normal;\n"
"    font-weight: 500;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255,255,255,80) ;\n"
"    padding : 4px ;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"  background-color: #ccc;\n"
"  color: #999;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QLineEdit {\n"
"    background-color: #f4f5f6 ;\n"
"    border-radius: 5px;\n"
"    color : #858585 ;\n"
"    border: 2px solid rgba(61,180,170,80);\n"
"    padding-left: 12px;\n"
"\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgba(61,180,170,255) ;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgba(61,180,170,255) ;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox {\n"
"    border-radius: 0px;\n"
"    color :white  ;\n"
"    border: 1px solid rgba(61,180,170,255);\n"
"    padding-left: 12px;\n"
"    padding-right: 12px;\n"
"    padding-top : 7px ;\n"
"    padding-bottom : 7px ;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"    background-color : #1b1e23  ;\n"
"}\n"
"\n"
"\n"
"QComboBox::drop-down {\n"
"      subcontrol-origin: padding;\n"
"    subcontrol-position: top left;\n"
"    border-left-width: 0px;\n"
"    border-left-style: solid; \n"
"    \n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/image/DownArrow_white.png);\n"
"     width: 16px; \n"
"     height: 16px;\n"
"    padding-left : 10px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QTextEdit {\n"
"    background-color: #f4f5f6 ;\n"
"    border-radius: 5px;\n"
"    color : #858585 ;\n"
"    border: 2px solid rgba(61,180,170,80);\n"
"    padding-left: 12px;\n"
"\n"
"}\n"
"QTextEdit:hover {\n"
"    border: 2px solid rgba(61,180,170,255) ;\n"
"}\n"
"QTextEdit:focus {\n"
"    border: 2px solid  rgba(61,180,170,255);\n"
"}\n"
"\n"
"QTableWidget {\n"
"    border : none ; \n"
"     background-color: #f0fff7;\n"
"    alternate-background-color: white;\n"
"    color : black;\n"
"    border-radius: 8px;\n"
"   \n"
"}\n"
"      \n"
"QHeaderView::section {\n"
"    background-color:  rgba(61,180,170,255);\n"
"    padding: 4px;\n"
"    border: none;\n"
"    color : white ;\n"
"}\n"
"\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color:  #9bffcd;\n"
"   \n"
"}\n"
"\n"
"QProgressBar {\n"
"    border: none;\n"
"    border-radius: 1px;\n"
"    background : #f0fff7\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: rgba(61,180,170,255);\n"
"}\n"
"\n"
"\n"
"QScrollBar:horizontal {\n"
"     border: none;\n"
"    background: none;\n"
"    width: 4px;\n"
"    margin: 21px 0 21px 0;\n"
"   border-radius: 2px;\n"
" }\n"
"\n"
" QScrollBar::handle:horizontal { \n"
"       background: rgba(61,180,170,255);\n"
"        min-height: 25px;\n"
"       border-radius: 2px;\n"
" }\n"
" QScrollBar::add-line:horizontal {\n"
"     border: none;\n"
"    background: none;\n"
"    \n"
" }\n"
" QScrollBar::sub-line:horizontal {\n"
"       border: none;\n"
"     background: transparent;\n"
"     \n"
" }\n"
" QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:horizontal, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"\n"
"QScrollBar:vertical {\n"
"     border: none;\n"
"    background: none;\n"
"    width: 4px;\n"
"    margin: 21px 0 21px 0;\n"
"   border-radius: 2px;\n"
" }\n"
"\n"
" QScrollBar::handle:vertical { \n"
"       background: rgba(61,180,170,255);\n"
"        min-height: 25px;\n"
"       border-radius: 2px;\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: none;\n"
"    \n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"       border: none;\n"
"     background: transparent;\n"
"     \n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget_main = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_main.setStyleSheet("")
        self.stackedWidget_main.setObjectName("stackedWidget_main")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setContentsMargins(0, 90, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setMinimumSize(QtCore.QSize(450, 300))
        self.label.setMaximumSize(QtCore.QSize(450, 300))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/image/dlpng_com_gym-icon-png-kansas-city-5_-_Be_Different_Fitness_6316801 1 (1).png"))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setStyleSheet("\n"
"font: 45px \"Inter\";\n"
"font-weight: 700;\n"
"color : white ")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 62, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setStyleSheet("font-family: \'Poppins\';\n"
"font-weight: 400;\n"
"color : white \n"
"")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 85, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.get_started_pushButton = QtWidgets.QPushButton(self.page)
        self.get_started_pushButton.setMinimumSize(QtCore.QSize(315, 48))
        self.get_started_pushButton.setMaximumSize(QtCore.QSize(315, 48))
        self.get_started_pushButton.setObjectName("get_started_pushButton")
        self.verticalLayout.addWidget(self.get_started_pushButton, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.stackedWidget_main.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setContentsMargins(20, 20, 20, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalWidget = QtWidgets.QWidget(self.page_2)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.horizontalWidget)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalWidget)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.verticalLayout_3.addWidget(self.horizontalWidget, 0, QtCore.Qt.AlignRight)
        self.rotate_pushButton = QtWidgets.QPushButton(self.page_2)
        self.rotate_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.rotate_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.rotate_pushButton.setStyleSheet("background-color : none ")
        self.rotate_pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/icons8-update-left-rotation-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotate_pushButton.setIcon(icon1)
        self.rotate_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.rotate_pushButton.setCheckable(True)
        self.rotate_pushButton.setObjectName("rotate_pushButton")
        self.verticalLayout_3.addWidget(self.rotate_pushButton, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget = QtWidgets.QStackedWidget(self.page_2)
        self.stackedWidget.setMinimumSize(QtCore.QSize(618, 500))
        self.stackedWidget.setMaximumSize(QtCore.QSize(618, 500))
        self.stackedWidget.setStyleSheet("background-color : transparent ; ")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stackedWidget.setObjectName("stackedWidget")
        self.front_page = QtWidgets.QWidget()
        self.front_page.setObjectName("front_page")
        self.label_4 = QtWidgets.QLabel(self.front_page)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 618, 500))
        self.label_4.setMinimumSize(QtCore.QSize(618, 500))
        self.label_4.setMaximumSize(QtCore.QSize(618, 500))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/image/front.png"))
        self.label_4.setObjectName("label_4")
        self.gridLayoutWidget = QtWidgets.QWidget(self.front_page)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(220, 180, 191, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_front = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_front.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_front.setObjectName("gridLayout_front")
        self.widget_2 = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widget_2.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_2.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_2.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_front.addWidget(self.widget_2, 0, 0, 1, 1)
        self.widget_14 = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widget_14.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_14.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_14.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_14.setObjectName("widget_14")
        self.gridLayout_front.addWidget(self.widget_14, 1, 5, 1, 1)
        self.widget_12 = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widget_12.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_12.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_12.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_12.setObjectName("widget_12")
        self.gridLayout_front.addWidget(self.widget_12, 1, 3, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widget_6.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_6.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_6.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_front.addWidget(self.widget_6, 0, 3, 1, 1)
        self.widget = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widget.setMinimumSize(QtCore.QSize(12, 12))
        self.widget.setMaximumSize(QtCore.QSize(12, 12))
        self.widget.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget.setObjectName("widget")
        self.gridLayout_front.addWidget(self.widget, 0, 5, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widget_7.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_7.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_7.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_front.addWidget(self.widget_7, 0, 2, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widget_3.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_3.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_3.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_front.addWidget(self.widget_3, 0, 4, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widget_8.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_8.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_8.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_front.addWidget(self.widget_8, 0, 1, 1, 1)
        self.widget_13 = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widget_13.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_13.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_13.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_13.setObjectName("widget_13")
        self.gridLayout_front.addWidget(self.widget_13, 1, 4, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widget_9.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_9.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_9.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_front.addWidget(self.widget_9, 1, 0, 1, 1)
        self.widget_11 = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widget_11.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_11.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_11.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_front.addWidget(self.widget_11, 1, 2, 1, 1)
        self.widget_10 = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widget_10.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_10.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_10.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_front.addWidget(self.widget_10, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.front_page)
        self.back_page = QtWidgets.QWidget()
        self.back_page.setObjectName("back_page")
        self.label_6 = QtWidgets.QLabel(self.back_page)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 618, 500))
        self.label_6.setMinimumSize(QtCore.QSize(618, 500))
        self.label_6.setMaximumSize(QtCore.QSize(618, 500))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/image/back.png"))
        self.label_6.setObjectName("label_6")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.back_page)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(220, 180, 191, 51))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_back = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_back.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_back.setObjectName("gridLayout_back")
        self.widget_30 = QtWidgets.QWidget(self.gridLayoutWidget_2)
        self.widget_30.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_30.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_30.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_30.setObjectName("widget_30")
        self.gridLayout_back.addWidget(self.widget_30, 0, 3, 1, 1)
        self.widget_29 = QtWidgets.QWidget(self.gridLayoutWidget_2)
        self.widget_29.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_29.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_29.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_29.setObjectName("widget_29")
        self.gridLayout_back.addWidget(self.widget_29, 0, 5, 1, 1)
        self.widget_31 = QtWidgets.QWidget(self.gridLayoutWidget_2)
        self.widget_31.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_31.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_31.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_31.setObjectName("widget_31")
        self.gridLayout_back.addWidget(self.widget_31, 1, 3, 1, 1)
        self.widget_34 = QtWidgets.QWidget(self.gridLayoutWidget_2)
        self.widget_34.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_34.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_34.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_34.setObjectName("widget_34")
        self.gridLayout_back.addWidget(self.widget_34, 1, 4, 1, 1)
        self.widget_36 = QtWidgets.QWidget(self.gridLayoutWidget_2)
        self.widget_36.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_36.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_36.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_36.setObjectName("widget_36")
        self.gridLayout_back.addWidget(self.widget_36, 1, 1, 1, 1)
        self.widget_27 = QtWidgets.QWidget(self.gridLayoutWidget_2)
        self.widget_27.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_27.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_27.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_27.setObjectName("widget_27")
        self.gridLayout_back.addWidget(self.widget_27, 0, 0, 1, 1)
        self.widget_32 = QtWidgets.QWidget(self.gridLayoutWidget_2)
        self.widget_32.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_32.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_32.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_32.setObjectName("widget_32")
        self.gridLayout_back.addWidget(self.widget_32, 0, 2, 1, 1)
        self.widget_39 = QtWidgets.QWidget(self.gridLayoutWidget_2)
        self.widget_39.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_39.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_39.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_39.setObjectName("widget_39")
        self.gridLayout_back.addWidget(self.widget_39, 1, 0, 1, 1)
        self.widget_26 = QtWidgets.QWidget(self.gridLayoutWidget_2)
        self.widget_26.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_26.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_26.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_26.setObjectName("widget_26")
        self.gridLayout_back.addWidget(self.widget_26, 0, 4, 1, 1)
        self.widget_33 = QtWidgets.QWidget(self.gridLayoutWidget_2)
        self.widget_33.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_33.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_33.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_33.setObjectName("widget_33")
        self.gridLayout_back.addWidget(self.widget_33, 0, 1, 1, 1)
        self.widget_35 = QtWidgets.QWidget(self.gridLayoutWidget_2)
        self.widget_35.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_35.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_35.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_35.setObjectName("widget_35")
        self.gridLayout_back.addWidget(self.widget_35, 1, 5, 1, 1)
        self.widget_38 = QtWidgets.QWidget(self.gridLayoutWidget_2)
        self.widget_38.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_38.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_38.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_38.setObjectName("widget_38")
        self.gridLayout_back.addWidget(self.widget_38, 1, 2, 1, 1)
        self.stackedWidget.addWidget(self.back_page)
        self.left_page = QtWidgets.QWidget()
        self.left_page.setObjectName("left_page")
        self.label_7 = QtWidgets.QLabel(self.left_page)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 618, 500))
        self.label_7.setMinimumSize(QtCore.QSize(618, 500))
        self.label_7.setMaximumSize(QtCore.QSize(618, 500))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/image/left.png"))
        self.label_7.setObjectName("label_7")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.left_page)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(310, 170, 91, 51))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_left = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_left.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_left.setObjectName("gridLayout_left")
        self.widget_56 = QtWidgets.QWidget(self.gridLayoutWidget_3)
        self.widget_56.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_56.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_56.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_56.setObjectName("widget_56")
        self.gridLayout_left.addWidget(self.widget_56, 0, 1, 1, 1)
        self.widget_60 = QtWidgets.QWidget(self.gridLayoutWidget_3)
        self.widget_60.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_60.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_60.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_60.setObjectName("widget_60")
        self.gridLayout_left.addWidget(self.widget_60, 1, 0, 1, 1)
        self.widget_57 = QtWidgets.QWidget(self.gridLayoutWidget_3)
        self.widget_57.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_57.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_57.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_57.setObjectName("widget_57")
        self.gridLayout_left.addWidget(self.widget_57, 0, 0, 1, 1)
        self.widget_62 = QtWidgets.QWidget(self.gridLayoutWidget_3)
        self.widget_62.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_62.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_62.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_62.setObjectName("widget_62")
        self.gridLayout_left.addWidget(self.widget_62, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.left_page)
        self.right_page = QtWidgets.QWidget()
        self.right_page.setObjectName("right_page")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.right_page)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(240, 170, 91, 51))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_right = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_right.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_right.setObjectName("gridLayout_right")
        self.widget_58 = QtWidgets.QWidget(self.gridLayoutWidget_4)
        self.widget_58.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_58.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_58.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_58.setObjectName("widget_58")
        self.gridLayout_right.addWidget(self.widget_58, 0, 1, 1, 1)
        self.widget_61 = QtWidgets.QWidget(self.gridLayoutWidget_4)
        self.widget_61.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_61.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_61.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_61.setObjectName("widget_61")
        self.gridLayout_right.addWidget(self.widget_61, 1, 0, 1, 1)
        self.widget_59 = QtWidgets.QWidget(self.gridLayoutWidget_4)
        self.widget_59.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_59.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_59.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_59.setObjectName("widget_59")
        self.gridLayout_right.addWidget(self.widget_59, 0, 0, 1, 1)
        self.widget_63 = QtWidgets.QWidget(self.gridLayoutWidget_4)
        self.widget_63.setMinimumSize(QtCore.QSize(12, 12))
        self.widget_63.setMaximumSize(QtCore.QSize(12, 12))
        self.widget_63.setStyleSheet("border: none;\n"
"border-radius: 6px;\n"
"background-color : white ; \n"
"")
        self.widget_63.setObjectName("widget_63")
        self.gridLayout_right.addWidget(self.widget_63, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.right_page)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 618, 500))
        self.label_8.setMinimumSize(QtCore.QSize(618, 500))
        self.label_8.setMaximumSize(QtCore.QSize(618, 500))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/image/right.png"))
        self.label_8.setObjectName("label_8")
        self.label_8.raise_()
        self.gridLayoutWidget_4.raise_()

        self.stackedWidget.addWidget(self.right_page)

        self.image_page_xy = QtWidgets.QWidget()
        self.image_page_xy.setObjectName("image_page_xy")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.image_page_xy)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, -1, 611, 501))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")

        fig_size = (10,10)
        self.figure = Figure(figsize=fig_size, facecolor='none')
        self.canvas = FigureCanvas(self.figure)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvas.sizePolicy().hasHeightForWidth())
        self.canvas.setSizePolicy(sizePolicy)
        # self.canvas.updateGeometry(self)
        self.ax = self.figure.subplots()
        self.ax.set_axis_off()
        self.ax.set_facecolor('none')
        self.horizontalLayout_5.addWidget(self.canvas)

        self.verticalSlider_xy = QtWidgets.QSlider(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalSlider_xy.sizePolicy().hasHeightForWidth())
        self.verticalSlider_xy.setSizePolicy(sizePolicy)
        self.verticalSlider_xy.setMaximum(45)
        self.verticalSlider_xy.setPageStep(5)
        self.verticalSlider_xy.setInvertedAppearance(True)
        self.verticalSlider_xy.setInvertedControls(True)
        self.verticalSlider_xy.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_xy.setTickPosition(QtWidgets.QSlider.TicksRight)
        self.verticalSlider_xy.setTickInterval(5)
        self.verticalSlider_xy.setObjectName("verticalSlider")
        self.horizontalLayout_5.addWidget(self.verticalSlider_xy)
        self.stackedWidget.addWidget(self.image_page_xy)

        ## yz page
        self.image_page_yz = QtWidgets.QWidget()
        self.image_page_yz.setObjectName("image_page_yz")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.image_page_yz)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, -1, 611, 501))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")

        self.figure2 = Figure(figsize=fig_size, facecolor='none')
        self.canvas2 = FigureCanvas(self.figure2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvas2.sizePolicy().hasHeightForWidth())
        self.canvas2.setSizePolicy(sizePolicy)
        # self.canvas2.updateGeometry(self)
        self.ax2 = self.figure2.subplots()
        self.ax2.set_axis_off()
        self.ax2.set_facecolor('none')
        self.horizontalLayout_6.addWidget(self.canvas2)

        self.verticalSlider_yz = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalSlider_yz.sizePolicy().hasHeightForWidth())
        self.verticalSlider_yz.setSizePolicy(sizePolicy)
        self.verticalSlider_yz.setMaximum(17)
        self.verticalSlider_yz.setPageStep(5)
        self.verticalSlider_yz.setInvertedAppearance(True)
        self.verticalSlider_yz.setInvertedControls(True)
        self.verticalSlider_yz.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_yz.setTickPosition(QtWidgets.QSlider.TicksRight)
        self.verticalSlider_yz.setTickInterval(5)
        self.verticalSlider_yz.setObjectName("verticalSlider_yz")
        self.horizontalLayout_6.addWidget(self.verticalSlider_yz)
        self.stackedWidget.addWidget(self.image_page_yz)

        ## xz page
        self.image_page_xz = QtWidgets.QWidget()
        self.image_page_xz.setObjectName("image_page_xz")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.image_page_xz)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, -1, 611, 501))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")

        self.figure3 = Figure(figsize=fig_size, facecolor='none')
        self.canvas3 = FigureCanvas(self.figure3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvas3.sizePolicy().hasHeightForWidth())
        self.canvas3.setSizePolicy(sizePolicy)
        # self.canvas3.updateGeometry(self)
        self.ax3 = self.figure3.subplots()
        self.ax3.set_axis_off()
        self.ax3.set_facecolor('none')
        self.horizontalLayout_7.addWidget(self.canvas3)

        self.verticalSlider_xz = QtWidgets.QSlider(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalSlider_xz.sizePolicy().hasHeightForWidth())
        self.verticalSlider_xz.setSizePolicy(sizePolicy)
        self.verticalSlider_xz.setMaximum(17)
        self.verticalSlider_xz.setPageStep(5)
        self.verticalSlider_xz.setInvertedAppearance(True)
        self.verticalSlider_xz.setInvertedControls(True)
        self.verticalSlider_xz.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_xz.setTickPosition(QtWidgets.QSlider.TicksRight)
        self.verticalSlider_xz.setTickInterval(5)
        self.verticalSlider_xz.setObjectName("verticalSlider_xz")
        self.horizontalLayout_7.addWidget(self.verticalSlider_xz)
        self.stackedWidget.addWidget(self.image_page_xz)


        self.verticalLayout_3.addWidget(self.stackedWidget, 0, QtCore.Qt.AlignHCenter)
        x = 0
        y = 0
        w = 1130
        h = 61
        self.colorbar = ImageColorbar(self.page_2, x, y,      w, h, show_colorbar=True, show_labels=False)
        self.labelBar = ImageColorbar(self.page_2, x, y+h,    w, 20, show_colorbar=False, show_labels=True)
        self.verticalLayout_3.addWidget(self.colorbar, alignment=QtCore.Qt.AlignCenter)
        self.verticalLayout_3.addWidget(self.labelBar, alignment=QtCore.Qt.AlignCenter)

        self.horizontalSlider = QtWidgets.QSlider(self.page_2)
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(500)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setPageStep(10)
        self.horizontalSlider.setProperty("value", 10)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_3.addWidget(self.horizontalSlider)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.label_9 = QtWidgets.QLabel(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)

        self.label_9.setVisible(False)
        self.label_10.setVisible(False)
        self.horizontalSlider.setVisible(False)
        self.colorbar.setVisible(False)
        self.labelBar.setVisible(False)

        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setStyleSheet("\n"
"font: 45px \"Inter\";\n"
"font-weight: 700;\n"
"color : white ")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.check_connection_pushButton = QtWidgets.QPushButton(self.page_2)
        self.check_connection_pushButton.setMinimumSize(QtCore.QSize(315, 48))
        self.check_connection_pushButton.setMaximumSize(QtCore.QSize(315, 48))
        self.check_connection_pushButton.setObjectName("check_connection_pushButton")
        self.horizontalLayout_2.addWidget(self.check_connection_pushButton)
        self.adjust_electrodes_connection_pushButton = QtWidgets.QPushButton(self.page_2)
        self.adjust_electrodes_connection_pushButton.setEnabled(False)
        self.adjust_electrodes_connection_pushButton.setMinimumSize(QtCore.QSize(315, 48))
        self.adjust_electrodes_connection_pushButton.setMaximumSize(QtCore.QSize(315, 48))
        self.adjust_electrodes_connection_pushButton.setObjectName("adjust_electrodes_connection_pushButton")
        self.horizontalLayout_2.addWidget(self.adjust_electrodes_connection_pushButton)
        self.view_impedance_connection_pushButton = QtWidgets.QPushButton(self.page_2)
        self.view_impedance_connection_pushButton.setEnabled(False)
        self.view_impedance_connection_pushButton.setMinimumSize(QtCore.QSize(315, 48))
        self.view_impedance_connection_pushButton.setMaximumSize(QtCore.QSize(315, 48))
        self.view_impedance_connection_pushButton.setObjectName("view_impedance_connection_pushButton")
        self.horizontalLayout_2.addWidget(self.view_impedance_connection_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem6)
        self.stackedWidget_main.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget_main.addWidget(self.page_4)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget_main.addWidget(self.page_3)
        self.verticalLayout_2.addWidget(self.stackedWidget_main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actiontest = QtWidgets.QAction(MainWindow)
        self.actiontest.setObjectName("actiontest")
        self.actiontest_2 = QtWidgets.QAction(MainWindow)
        self.actiontest_2.setObjectName("actiontest_2")
        self.actiontest_3 = QtWidgets.QAction(MainWindow)
        self.actiontest_3.setObjectName("actiontest_3")
        self.actiontest_4 = QtWidgets.QAction(MainWindow)
        self.actiontest_4.setObjectName("actiontest_4")

        self.retranslateUi(MainWindow)
        self.stackedWidget_main.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EIT App"))
        self.label_2.setText(_translate("MainWindow", "Get EIT\n"
"Readings"))
        self.label_3.setText(_translate("MainWindow", "View  EIT Harness Measurements "))
        self.get_started_pushButton.setText(_translate("MainWindow", "Get Started"))
        self.radioButton.setText(_translate("MainWindow", "16"))
        self.radioButton_2.setText(_translate("MainWindow", "32"))
        self.label_10.setText(_translate("MainWindow", "0.1"))
        self.label_9.setText(_translate("MainWindow", "50"))
        self.label_5.setText(_translate("MainWindow", "Connect \n"
"Electrods "))
        self.check_connection_pushButton.setText(_translate("MainWindow", "Check Connection ..."))
        self.adjust_electrodes_connection_pushButton.setText(_translate("MainWindow", "Adjust electrodes "))
        self.view_impedance_connection_pushButton.setText(_translate("MainWindow", "View Impedance"))
        self.actiontest.setText(_translate("MainWindow", "test"))
        self.actiontest_2.setText(_translate("MainWindow", "test"))
        self.actiontest_3.setText(_translate("MainWindow", "test"))
        self.actiontest_4.setText(_translate("MainWindow", "test"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
